name: 'Rami Code Review'
description: 'Wait for AI-powered code review results on your pull requests'
author: 'rami-code-review'

branding:
  icon: 'eye'
  color: 'purple'

inputs:
  fail_on:
    description: 'Severity level that causes the action to fail: blocking, high, medium, low, none'
    required: false
    default: 'low'

outputs:
  status:
    description: 'Review status: clean, issues_found, blocked, not_found, in_progress, or error'
  total_issues:
    description: 'Total number of issues found'
  blocking_count:
    description: 'Number of blocking issues'
  high_count:
    description: 'Number of high severity issues'
  medium_count:
    description: 'Number of medium severity issues'
  low_count:
    description: 'Number of low severity issues'
  files_reviewed:
    description: 'Number of files reviewed'
  review_url:
    description: 'URL to the reviewed PR'

runs:
  using: 'node20'
  main: 'dist/index.js'
